#!/bin/bash
if [ "$*" == "" ]; then
  echo "run peers initialPort"
  exit;
fi

gnome-terminal -e "bash 'cd $PWD && java -cp gson-2.8.5.jar:. DFSCommand $2'"

for ((i = 1; i < $1; i++));
do
  port=$(($i + $2))
  gnome-terminal -e "bash 'cd $PWD && java -cp gson-2.8.5.jar:. DFSCommand $port $2'"

done
